FROM golang:1.10

RUN apt-get update && apt-get install unzip && apt-get clean

LABEL maintainer="Smita Shetty<smita.narasimha@gmail.com>"

# copy files from /internal

# protoc 

# go build

# start server