FROM golang:1.10

RUN apt-get update && apt-get install unzip && apt-get clean

ENV Pub_Ver 3.6.0

ENV Pub_Url https://github.com/google/protobuf/releases/download/v${Pub_Ver}/protoc-${Pub_Ver}-linux-x86_64.zip

RUN mkdir -p /tmp/protoc && \
	curl -L ${Pub_Ver} > /tmp/protoc/protoc.zip && \
	rm -r /tmp/protoc

RUN mkdir -p /tmp/grpc-go && \
	curl -L https://github.com/grpc/grpc-go/archive/v1.0.0.zip > /tmp/grpc-go/grpc-go.zip && \
	cd /tmp/grpc-go && \
	unzip grpc-go.zip && \
	mkdir -p /go/src/google.golang.org/grpc/ && \
	cp -r /tmp/grpc-go/grpc-go-1.0.0/* /go/src/google.golang.org/grpc/ 

RUN mkdir -p /tmp/protobuf && \
	curl -L https://github.com/golang/protobuf/archive/v1.1.0.zip > /tmp/protobuf/protobuf.zip && \
	cd /tmp/protobuf && \
	unzip protobuf.zip && \
	mkdir -p /go/src/github.com/golang/protobuf/ && \
	cp -r /tmp/protobuf/protobuf-1.1.0/* /go/src/github.com/golang/protobuf/ && \
	go install github.com/golang/protobuf/protoc-gen-go

